"""Update ServiceOrder model: change service_date to Date, add service_time

Revision ID: 61e6e61fdfa4
Revises: 997d726eca18
Create Date: 2025-06-04 21:15:08.531037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e6e61fdfa4'
down_revision = '997d726eca18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_date_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('service_time_at', sa.Time(), nullable=True))
        batch_op.drop_column('service_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('service_time_at')
        batch_op.drop_column('service_date_on')

    # ### end Alembic commands ###
