"""Add is_admin to User model and update password_hash nullability

Revision ID: 997d726eca18
Revises: 46265afb4937
Create Date: 2025-06-04 21:11:34.956476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997d726eca18'
down_revision = '46265afb4937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
