"""Add detailed models for all service order components and relationships

Revision ID: d289f8986a2c
Revises: 61e6e61fdfa4
Create Date: 2025-06-04 22:21:14.385441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd289f8986a2c'
down_revision = '61e6e61fdfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deportees_accused',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('charge', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('female_staff_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('is_officer_in_charge', sa.Boolean(), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jurisdiction_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('accompanying_entity', sa.String(length=200), nullable=True),
    sa.Column('responsible_person_title', sa.String(length=100), nullable=True),
    sa.Column('responsible_person_name', sa.String(length=150), nullable=True),
    sa.Column('responsible_person_phone', sa.String(length=50), nullable=True),
    sa.Column('responsible_person_email', sa.String(length=120), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_order_id')
    )
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('officer_type', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_force_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('force_type', sa.String(length=50), nullable=True),
    sa.Column('group_leader_type', sa.String(length=50), nullable=True),
    sa.Column('group_leader_rank', sa.String(length=100), nullable=True),
    sa.Column('group_leader_name', sa.String(length=150), nullable=True),
    sa.Column('group_leader_phone', sa.String(length=50), nullable=True),
    sa.Column('group_count', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('vehicle_driver_rank', sa.String(length=100), nullable=True),
    sa.Column('vehicle_driver_name', sa.String(length=150), nullable=True),
    sa.Column('vehicle_driver_phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_order_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('clause_type', sa.String(length=50), nullable=True),
    sa.Column('clause_number', sa.String(length=100), nullable=True),
    sa.Column('clause_document', sa.String(length=200), nullable=True),
    sa.Column('additional_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_category', sa.String(length=100), nullable=True),
    sa.Column('chief_type', sa.String(length=50), nullable=True),
    sa.Column('chief_rank', sa.String(length=100), nullable=True),
    sa.Column('chief_name', sa.String(length=150), nullable=True),
    sa.Column('chief_phone', sa.String(length=50), nullable=True),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('driver_rank', sa.String(length=100), nullable=True),
    sa.Column('driver_name', sa.String(length=150), nullable=True),
    sa.Column('driver_phone', sa.String(length=50), nullable=True),
    sa.Column('driver_license_number', sa.String(length=50), nullable=True),
    sa.Column('capacity_load', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_orders', schema=None) as batch_op:
        batch_op.drop_column('security_level')

    op.drop_table('vehicles')
    op.drop_table('service_order_clauses')
    op.drop_table('security_force_groups')
    op.drop_table('officers')
    op.drop_table('jurisdiction_info')
    op.drop_table('female_staff_members')
    op.drop_table('documents')
    op.drop_table('deportees_accused')
    # ### end Alembic commands ###
